### ISSUE TITLE
maxAge and isPromise are preventing Jest from exiting gracefully

### ISSUE THREAD

**Issue by stevenhair** [planttheidea/moize#119]
When using the `maxAge` option, tests are not exiting even if the cache is cleared at the end of the test. Tests will exit once the cache has expired, so I'm guessing that timers aren't being cleared after the items are removed from the cache.

I tried working around this by clearing the timeouts directly by calling `myFunction.expirations.map((e) => clearTimeout(e.timeoutId))`, but that didn't solve the problem either.

Here's my output from Jest:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  Timeout

      49 |     describe('When the feature flag does not exist', () => {
      50 |         it('the flag is always reported as off', async () => {
    > 51 |             await expect(featureFlagRepo.isFlagOn('foo', true, user)).resolves.toBe(false);
         |                                          ^
      52 |             await expect(featureFlagRepo.isFlagOn('bar', false, user)).resolves.toBe(false);
      53 |         });
      54 |     });

      at onCacheAdd (../node_modules/moize/lib/maxAge.js:92:20)
      at ../node_modules/moize/lib/options.js:22:9
      at MongoFeatureFlagRepository.memoized (../node_modules/micro-memoize/lib/index.js:108:7)
      at Object.<anonymous> (persistence/feature-flags/mongo-feature-flag.repository.spec.ts:51:42)
```

**Comment by planttheidea** [comment]
Thanks for reaching out! If you can give me this information:

- What is the `options` setup for `moize`? Is it _only_ `maxAge`, or are there other options in concert?
- How are you clearing the cache?

Hopefully with this I can build a targeted repro. Or, if you were to provide me a simple repro, even better!

**Comment by stevenhair** [comment]
I attempted to make a simple reproduction, but I was unable to. The issue appears to be more complex than I thought. I'll continue trying to reproduce it - if I can't come up with something, I'll close this issue.

**Comment by stevenhair** [comment]
Here's a working reproduction: https://github.com/stevenhair/probable-bassoon

The issue is only present when tests are run in parallel.

**Comment by planttheidea** [comment]
This is very helpful, thank you. I'll take a look at this during the weekend, hopefully find some answers for you.

**Comment by stevenhair** [comment]
Thank you for taking a look!

**Comment by planttheidea** [comment]
Alright I've tried looking into this for the last hour, but its tough because `npm` isn't completing installation ... something must be down, it says there is a problem with my network but I've verified everything is fine on my end. This means I cannot (yet) use your example repo; I'll keep trying, but it may take a while as finding time is hard these days.

Either way, based on the stack trace I dove into the code to try to see if anything stood out. Nothing surprising, in that it calls out the area where the `setTimeout` occurs for the expiration, so there is a lingering timeout at the conclusion of the tests (as `.resolve()` will fire before the 1s timing). What surprises me is that manually clearing out the timeouts did not work, because that should handle it (in an `afterEach` or something along those lines). This is why I wanted to look into it; if I were going to offer initial advise it would be something like:

```ts
describe('Bar', () => {
	afterEach(() => {
		[...add.expirations].forEach((expiration) => {
			// clear the timeout
			clearTimeout(expiration.timeoutId);

			// remove it from expirations
			add.expirations.splice(0, 1);
		});
	});

    describe('When adding two numbers', () => {
        it('it adds the numbers', async () => {
            await expect(add(3, 2)).resolves.toEqual(5);
        });
    });
});
```

Once I can finally get your repo working I'll dive back into it, but I'm blocked for now. Just giving an update, this isn't forgotten.

**Comment by planttheidea** [comment]
Alright I go things working again, and by running the default tests I see the same warning you discuss. Once applying the same `afterEach` usage above to both `Foo` and `Bar`, I no longer see the warning, so the recommendation I was going to provide appears to hold true.

I've created a [PR that has this test cleanup applied](https://github.com/stevenhair/probable-bassoon/pull/1) so that you can see an example. Hopefully this helps out.

**Comment by stevenhair** [comment]
Ah, I just cleared the timeouts without setting the length to zero, maybe that was the issue. I also suspect that there was something strange happening with the MongoDB client behind the scenes. I'll add this to my real code and see what happens.

Would you consider this a workaround? If not, maybe it would be worth adding a method to moize to clear the timeouts? I can open a PR for that if you think that it would be useful.

**Comment by planttheidea** [comment]
Honestly I've been avoiding test-only utilities like this because of unknown scope; it would with either be application-specific it would eventually have enough use cases to warrant it's own package (think `moxios` as a compliment to `axios`). Either way, I didn't want to bloat runtime code for test only code.

What I would recommend is, assuming this works for your needs, just create a test helper that receives the function to clear and clears it. Reusable, quick to write, and minimal footprint.

**Comment by stevenhair** [comment]
Gotcha.

I just confirmed that this solves me issue. My implementation feels a bit hacky because I'm using moize in a decorator on a private class method, but it works. For anyone interested, I switched my method from private to protected and created a subclass in the test:

```typescript
class TestFooClass extends FooClass {
    clearTimeouts(): void {
        (this.myMethod as moize.Moized).expirations.forEach((e) => clearTimeout(e.timeoutId));
        (this.myMethod as moize.Moized).expirations.length = 0;
    }
}
```

and then I just call `clearTimeouts()` in an `afterEach()`.

Thanks for the quick feedback!
