### ISSUE TITLE
[Feature request] Dynamically skip memoization

### ISSUE THREAD

**Issue by ehmicky** [planttheidea/moize#124]
Users might want to bypass a function's memoization or explicitly invalidate a function's cache. One way to implement this could be (for example) with a `invalidateCache` boolean option. 

To implement this behavior with `moize`, the best way I could find is:

```js
const moizedFunc = moize(func, { maxArgs: 1 })
const cacheKeys = getCacheKeys(args)

if (args[0].shouldInvalidateCache) {
  moizedFunc.remove([cacheKeys])
}

moizedFunc(cacheKeys, args)
```

This solution is quite hacky. Also, if `moizedFunc` throws, `cacheKeys` should be added back, making the example above more complex.

I could also do:

```js
const moizedFunc = moize(func, { maxArgs: 1 })

if (args[0].shouldInvalidateCache) {
  return func(args)
}

return moizedFunc(args)
```

But this would not update the cache on success, which would make more sense, even when the cache is not being read.

A better way might be for `moize` to add an option to skip reading the cache, such as:

```js
moize(func, { 
  shouldReadCache(args) {
    return !args[0].shouldInvalidateCache
  }
})
```

When returning `false`, the cache would not be read. However, it would be still be written on success.

What do you think?

**Comment by planttheidea** [comment]
So it looks like you are asking for two things here, so I'll try to tackle each separately.

1) Conditional memoization usage

Based on "bypass memoization" it seems like you want the ability to only used memoized results conditionally? It would be odd, because it would kind of violate the "pure function" driver of memoization to begin with. That said, if you did have an impure function that you wanted to conditionally memoize, it seems like a simple wrapper could handle this.

```js
const fn = (a, b) => a + b;

const memoizedFn = moize(fn, { maxArgs: 1 });

function conditionalMemoizedFn(shouldUseCachedValues, ...args) {
  return shouldUseCachedValues ? memoizedFn(...args) : fn(...args);
}

conditionalMemoized(true, 1, 2); // use the memoized fn
conditionalMemoized(false, 1, 2); // use the fn directly
```

Because this is a rare use-case (and, as aforementioned, kind of antithetical to functional purity that memoization is based on), I would not want to introduce the runtime complexity to satisfy it.

2) Invalidate args conditionally

This is an interesting one, because I can see how this could be beneficial to the library as a whole, but its the implementation details that would need to be fleshed out. Remember this needs to be done programmatically, so we need to identify:
- Is it a true _removal_ of that result value (i.e., "it returns some value and therefore does not get stored"), or simply an _update_ of the cached result (i.e., "if X condition is met, re-call the function and store the result even if already cached")?
- If these changes occur, would they trigger additional calls to `onCacheAdd` / `onCacheChange` / `onCacheHit`?

I would again be wary of this because it has the potential to cause noticeable speed loss for an edge case, but definitely worth an exploration. If you can clarify the desired intent based on the questions above, I can start noodling over it.

In the meantime, another simple wrapper within your application can be effective here as well.

```js
const fn = (a, b) => a + b;

const memoizedFn = moize(fn, { maxArgs: 1 });

function refreshCachedValues(shouldRefresh, ...args) {
  if (shouldRefresh) {
    memoizedFn.remove(args);
  }

  return memoizedFn(...args);  
}

refreshCachedValues(true, 1, 2); // removes cached values and re-calls fn
refreshCachedValues(false, 1, 2); // use cache if it exists
```

**Comment by ehmicky** [comment]
Please note that the two examples above are similar to my first and second example, except with an additional level of indirection. I actually currently use the same pattern that you just illustrated, but I removed the additional function wrapping for example sake.

About the first point: memoization works best for pure functions, but using it on impure functions is a valid use case, and probably not so rare. For example, caching an HTTP request whose result changes from time to time.

Unfortunately, while the example does allow skipping reading the cache, it also skips writing it, which would be unfortunate in a scenario where a user would (for example) want to "force update" the memoization cache.

About the second point: I am not sure about which events would be triggered (I do not use those events). My use case would be the second one: updating (or not) the cache based on the `args` passed by the user, not removing. Maybe the speed can be optimized by not doing anything unless this feature has been opted in with a specific option?

**Comment by planttheidea** [comment]
FYI I've decided to table this for now, mainly due to logistics reasons. The change would actually need to happen to `micro-memoize` (`moize` is a wrapper around `micro-memoize` with a bunch of additional options) because that is where the cache management lies. The current version of `moize` uses an old version of `micro-memoize` under-the-hood, which means I would need to dust off and retroactively update all major versions of `micro-memoize`. I am already working on a major version update of `moize` (mainly a TS update, but also some new configuration options) that uses the latest `micro-memoize`, so once I am able to get that update out the door I will revisit this.

**Comment by ehmicky** [comment]
Thanks for the update @planttheidea!

**Comment by planttheidea** [comment]
Update!

I've just released the initial beta of the next major version (`6.0.0-beta.0` if you want to try), and as promised I was revisiting this feature request. It is not in the initial beta (I just wanted to get it out the door, its been a year coming), but I think I have an idea about how to accomplish this without touching the lower-level `micro-memoize` library.

Just to make sure I understand the intent, you want to have an option that allows the user to programmatically ignore any existing cache values for a given key (the arguments passed) and re-call the function directly. If this call is successful, then it would replace the existing cache value for those key, but if it fails it would revert to the existing cache value. Is this an accurate explanation?

Apologies if this is just regurgitating already-described details, I just haven't thought about this in a month and I want to make sure my recent idea would fulfill your request.

**Comment by ehmicky** [comment]
Thanks for following up on this!

Yes, this is an accurate description, except for the failure. On one hand, providing the existing cache value as fallback sounds good from a resilience standpoint. On the other hand, for my specific use case, I actually care more about making sure the cache is not being read, whether if the function call is successful or not. So I would expect any exception thrown to be propagated instead.

**Comment by planttheidea** [comment]
Ah yes okay, forgot about the error handling piece. No problem, I think that makes sense and would still work.

I'll work on this and report back.

**Comment by tquetano-netflix** [comment]
@ehmicky I have a PR open (above) that incorporates the new option that should facilitate this. If you wanted to give it a quick look and let me know if it meets your goals I'd appreciate it.

I won't be merging it until I update the documentation, but the feature and associated tests should be done.

**Comment by ehmicky** [comment]
Yes, this is looking good, thanks!

One question though: when `updateCacheForKey` returns `false`, while reading the cache is skipping, do you think it would make sense to still write the result to cache?

For example, an impure HTTP request which is cached might want to refresh the cache, which means it would ignore the cache on read, but still write it on result.

**Comment by planttheidea** [comment]
Not quite sure I'm following. The option would return `true` to update the cache... If it returned `false` it would call the memoized function like normal. Perhaps an example would help explain better.

**Comment by ehmicky** [comment]
```js
const moize = require('moize').default

let incrementValue = 0
const increment = function() {
  incrementValue += 1
  return incrementValue
}

const mIncrement = moize(increment, {
  updateCacheForKey({ force  }) {
    return force !== true
  }
})

console.log(mIncrement()) // 1. No cache yet.
console.log(mIncrement()) // 1. The previous call wrote to the cache, and this call reads it.
console.log(mIncrement({ force: true })) // 2. Does not read the cache.
console.log(mIncrement()) // 2. The previous call wrote to the cache, even though it did not read it.
```

When `updateCacheForKey` is `false`, should the return value be used in following memoized calls (i.e. should the cache be written to)?

**Comment by planttheidea** [comment]
This is actually exactly how the feature works when the call returns true ... Upon successful return it updates the cache with the new result.

To help clarify, the `updateForCacheKey` method determines if the cache should be updated, meaning the existing cache should be bypassed and updated with the new result. Hence, returning `true` will do exactly what you're describing.

**Comment by ehmicky** [comment]
Yes, you're correct about my example: I updated it so the `key` is always the same (for example sake).

I think what I'm trying to get at is the distinction between reading and updating the cache.
In the example above, the 4 calls to `mIncrement()` update the cache. However, only the first, second and last call would read the cache. So there are two behaviors:
  - normal behavior: reading + updating the cache
  - "refresh" behavior: does not read the cache, but still update it

**Comment by tquetano-netflix** [comment]
I think we may be going around and around on terminology here, because the result you seek is exactly how this new option is programmed to operate (with the exception that returning `true` from the option will trigger the "refresh" behavior, not `false`).

To answer what I believe to be the core aspect of your question, _the return value from the "refresh" will be used in following memoized calls_. This option does not simply bypass the cache, it will also update the value stored in cache for subsequent "normal behavior" calls.

**Comment by ehmicky** [comment]
Alright, this would be good then! Thanks for working on this!

**Comment by planttheidea** [comment]
This feature has been released in `6.0.0-beta.3`. Let me know if the documentation needs tweaking or if you have any issues.

FYI, I added a few more tests to the suite, including one specifically based on the example you provided.

Thanks for the request, and the continued interest in `moize`!

**Comment by ehmicky** [comment]
Thanks a lot @planttheidea!

**Comment by ehmicky** [comment]
I gave it a deeper testing, and it works as intended. Thanks @planttheidea!
