### ISSUE TITLE
Node 14 ESM imports fail

### ISSUE THREAD

**Issue by tozz** [planttheidea/moize#128]
Going by the README `import moize from 'moize/mjs'` is the way to import the module, unfortunately this doesn't work and it's not according to the Node requirements.
https://nodejs.org/api/esm.html
**A file extension must be provided when using the import keyword. Directory indexes (e.g. './startup/index.js') must also be fully specified.**

I can of course change this by doing `import moize from 'moize/mjs/index.mjs'` (it is however not exported as one would expect) but the failure cascades to the dependencies which all need to follow the file extension rule.

**Comment by planttheidea** [comment]
Sorry for the delay, it has been a wild month for me. If you'd like I can take a look at it this weekend, but the change should be pretty straightforward if you were willing to put together a PR:

1) Change Lines [29](https://github.com/planttheidea/moize/blob/master/es-to-mjs.js#L29) and [30](https://github.com/planttheidea/moize/blob/master/es-to-mjs.js#L30) in the `es-to-mjs.js` script to be `/mjs/index.mjs` instead of just `/mjs`
2) Update `README.md` to reflect the correct usage as you call out above.

**Comment by tozz** [comment]
GitHub notification got stuck in spam, thanks for the very clear instructions, opened a PR and I've tested it locally.

**Comment by planttheidea** [comment]
Thanks for the PR! I've released the changes with `5.4.7`, let me know if you have any more issues.

**Comment by tozz** [comment]
I was a bit premature, when I used the the code from a checkout locally the changes works, but using it from NPM it's back to cascading failures (micro-memoize and constants missing .mjs extensions throughout).
Looking at the code it makes perfect sense since the compiled output is different from the source one (imports are being created but not imported with the correct extensions).

**Comment by planttheidea** [comment]
Well this may be my own fault; the version on npm is not `master`, which is what your PR was to. I tried to apply the same changes on the `v5` branch with the same explicit file path. Therefore, what you tested locally was not what ended up being `5.4.7`.

First, if you want to try the beta and see if that works, that is your change so it should work as planned. If so, then we can focus on updating v5, and if not then we'll need to investigate further. I'll try to come up with a reasonable validation for it, or if you have a test I can incorporate it into the repo.

**Comment by planttheidea** [comment]
Ah nvm, I see the issue. It is because on v5 we are still using transpiled files instead of rollup for the build, so local `import` statements also fail. I'll work on this right now for v5, but I've confirmed it works as expected on the v6 beta.

**Comment by tozz** [comment]
Thanks for the quick turn around, I installed the beta version and it works as expected 👍🏻

**Comment by planttheidea** [comment]
Good, because I have bad news about v5. ☹️ Because the older dependencies are _also_ using transpiled files instead of rollup for their build, I don't think I can do this in a way that would not itself create a breaking change. It seems like v6 may be your only path forward for ESM usage in Node 14. Apologies.
