### ISSUE TITLE
Why does moize's performance implode in this test case?

### ISSUE THREAD

**Issue by Slapbox** [planttheidea/moize#138]
I forked off some existing tests on MeasureThat.net but was surprised to find that moize totally implodes when the argument is a new object that is equal in value, but not reference identity, to the previous one.

[Reference identity - 6.5% faster than memoize-one](https://www.measurethat.net/Benchmarks/Show/9708/0/memoized-object-assignment)
[Value equality - 50000% slower than memoize-one](https://www.measurethat.net/Benchmarks/Show/9710/0/memoized-object-assignment-new-objects---flat)

**Comment by planttheidea** [comment]
Valid question; there are a couple things at play here.

1) The "value equality" case is only testing "what do these functions do when values change every since time?". Because the object references change on every call, nothing is ever memoized.
2) The reason for the cost is because by default `moize` versions 5 and below will store _all previous values in cache_ unless a cache size is provided. This means that storage work and existing checks are being done for a constantly-growing cache base, which means an exponential increase in runtime cost and memory.

A more apples-to-apples comparison with `memoize-one` would not be to use `moize` but instead `moize.simple`, which limits the cache size to `1` (which is the hard-coded default for `memoize-one`). Or you can test with [the latest beta](https://www.npmjs.com/package/moize/v/6.0.0-beta.4), which changes the default cache size from `Infinity` to `1`, again providing a closer apples-to-apples.

**Comment by Slapbox** [comment]
Thanks for your reply! Looks like I misread the docs while skimming through. I had read it as `maxAge` defaults to `1` - overlooking that that was a reference to how `moize.simple` works.

Thanks also for the pointer about comparing using a custom `equals`. I'll look into that when I find some more time to allocate to benchmarking stuff.
