### ISSUE TITLE
Specify memoized function name

### ISSUE THREAD

**Issue by raineorshine** [planttheidea/moize#161]
Is there a way to specify the memoized function name for tools such as the Performance tab in Chrome? It makes it difficult to use if all of the memoized functions are called `memoized`.

Maybe it could use `profileName`?

![image](https://user-images.githubusercontent.com/750276/131223318-6d93977e-356b-460e-9315-96f47948d762.png)

**Comment by planttheidea** [comment]
Unfortunately, `function.name` is a read-only property, so I can't do much to customize it. Unless devtools supports a special property (like `displayName` in React Devtools) not much that can be done.

**Comment by planttheidea** [comment]
Actually I did a little research, and it looks like I can set it via `Object.defineProperty` since ES2015. I'll play with this, but if I can get it working it'll be something like `memoized(ORIGINAL_FUNCTION_NAME)`.

**Comment by planttheidea** [comment]
I've created the above PR to add support for this, but I was hoping on some feedback prior to merging and publishing.

Right now the priority of possible names are:
1. Original function name
2. `profileName`, if provided
3. Generic "anonymous" ultimate fallback

I'm curious if `profileName` should get priority over the original function name. I can see the argument that it is a unique identifier of the function, and since the primary purpose is to map in dev tools then it would naturally map to a different developer tools (profiling). Thoughts?

**Comment by raineorshine** [comment]
Awesome, thanks for looking into this! I'll take a look at the PR.

I believe `displayName` has been deprecated and `Object.defineProperty` to set `name` is the recommended approach.

**Comment by planttheidea** [comment]
`displayName` is specific to React components (still a common convention there).

**Comment by planttheidea** [comment]
Alright I have published this change in `6.1.0`. Let me know if you have any more issues!
