### ISSUE TITLE
types are wrong when micro-memoize is imported

### ISSUE THREAD

**Issue by rosmcmahon** [planttheidea/moize#206]
**steps to reproduce:**

- install `moize` 
- import as `micro-memoize`
- try using `maxAge` - it's available in the types for the micro-memoize function
- maxAge isn't available in micro-memoize though
- no warnings or errors thrown.

**Comment by planttheidea** [comment]
I'm not sure what you mean by "import as `micro-memoize`"; just because you alias the import as something doesn't mean it automatically becomes that something. Can you provide an example in code? I may understand what you are looking for a little better.

**Comment by rosmcmahon** [comment]
apologies for the delay. let me clarify if i can so:
start a project, install typescript, etc.
`npm i moize`
index.ts:
```ts
import moize from 'micro-memoize' // oops!

const myFun = moize(
	(a: number, b: number) => a + b,
	{
		maxAge: 60_000, // (property) maxAge: number  
	}
)
```

**Comment by planttheidea** [comment]
Ah I see. This may be more of a documentation issue, because I don't see this called in the README, but this is actually an expected outcome of `micro-memoize` conflated with the accidental usage with `moize`.

Basically, the options for `micro-memoize` (and `moize`) have defined properties, but they also basically allow _anything else_ to be added as a custom option. These can be used for different use-cases, such as being accessed from `memoized.options` to identify the memoized function. The accidental usage as `moize` combined with providing expected properties of `moize` options gives the impression that those options are somehow supported, but really it is just that you added something and TS is automatically inferring its type. [Here is an example where I've added an "incorrect" `moize` option to `micro-memoize` options, as well as random bunk](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBCApiCwBei4DMoRHAchGAGNcBaJFdRAgbgCgGSIA7AZ3hAE8AxAV1ZwAvAmSoMACgZxZcSQEMAXHFb8QAI0RQANHA0q1m7QEoRAPjgK4Aan06ZcgN4IFADwCCAc0QqCACwgAdwATbnIQiAgCPQ1gVi8AG0QAIWhfQhgFciyCOABfBxM6IA) to showcase what I mean.

I can follow up with a documentation update to call out how other options are transparently passed through to use as seen fit by consumers.

**Comment by rosmcmahon** [comment]
Thanks for the explanation! Closing
