### ISSUE TITLE
[Documentation needed] How does moize return a promise?

### ISSUE THREAD

**Issue by Redsandro** [planttheidea/moize#30]
When a function returns a promise and there is no cached result, will the unresolved promise be returned?
When cached, will a resolved promise be returned, or the value of the resolved promise?

**Comment by planttheidea** [comment]
Yeah I can update the documentation on this, but to answer the question:

* When no cached result is found, `moize` will return the unresolved promise but internally wait for the resolution of that promise and store the cached value
* When cached, a resolved promise will be returned

The caching of promises specifically was an area that I didn't spend a ton of time on writing, the implementation could probably use a review. I'll give it a once over this weekend and at bare minimum update the documentation for it, but also potentially improve it.

**Comment by Redsandro** [comment]
@planttheidea thank you for the quick clarification. :+1: 

Seems good. Adding that to the docs will probably clarify everything. As long as it will always return a promise, this is perfect.

**Comment by Redsandro** [comment]
@planttheidea oh one more thing for the docs: Please mention what promise library (or native) is used for returning the cached value. The API available for the promise depends on it.

Ideally, one can explicitly set the promise library (e.g. `q`, `bluebird`, `bbq` etc).

**Comment by planttheidea** [comment]
@Redsandro I am working on this today, and I am enhancing the handling of promise caching as such:
* Rejected promises will automatically remove themselves from cache (a common use case is AJAX calls and a temporary network blip should not persist the error in cache)
* The starting of the TTL will be upon resolution of the promise instead of upon instantiation of it
* A new `promiseLibrary` option will be available where you can pass in the library used if not native

I need to write several new tests for this enhancement, but I should be able to accomplish it by the end of the weekend.

**Comment by Redsandro** [comment]
Very nice @planttheidea, thank you :+1:

**Comment by planttheidea** [comment]
Aforementioned enhancements to the promise setup are released in `2.2.0`, and documentation has been updated with more details about both the `isPromise` and the new `promiseLibrary` options.

**Comment by Redsandro** [comment]
I like this. I'm going to play with it next week.

**Comment by planttheidea** [comment]
Cool, let me know if you encounter any issues. ☺️
