### ISSUE TITLE
iMemoized

### ISSUE THREAD

**Issue by anywhichway** [planttheidea/moize#5]
Suggest you take a look at https://github.com/anywhichway/iMemoized. It appears to be faster and is less than 1K when minified and gzipped. The article http://anywhichway.github.io/indexing.html describes the indexing approach if you wish to make moize faster.

**Comment by planttheidea** [comment]
First of all, appreciate you plugging your own package via github issue. Always a classy move.

Secondly, I really find the benchmark disclaimer notification you provide on your repository quite accurate:

*Note, these benchmarks may vary dramatically from environment to environment. We make no absolute claim that iMemoized is the fastest or fastest possible memoizer. You should test in your own environment.*

So I listened to that; I pulled down iMemoized and ran my exact same benchmarks with it added. The results:
* `iMemoize` is faster with a single parameter (by about 10%)
* `iMemoize` is slower (by about 4%) with multiple parameters that are primitives
* `iMemoize` is slower (by about 1,625%) with multiple parameters that are objects

The last one in particular is quite interesting, as I noticed you copied by multiple parameters that are primitives test, but for some reason decided to leave out the one that compares objects. I doubt it's related to the benchmarking results I just mentioned (where `moize` was more than 16x faster than `iMemoize`.

Finally, great work on getting that size down to less than 1K. Looking at your code base I'm certain the number of contributors will remain `1` for all time because its horrifically unreadable and scattered about, but damned if it isn't efficient.

Closing this as is it is not an issue.

**Comment by anywhichway** [comment]
@planttheidea Tony, seemed like GitHub was the easiest way to communicate. Leaving issue closed. Sorry if I offended you. No email address in your package.json. Give me an email and we can communicate that way if you wish.

Did not actually try to get the code to 1K, just a side-effect of the indexing mechanism. Code could certainly do with some comments though! It was written in just 2 hours on a challenge from someone. Have never really revisited the core.

Not actually trying to drive iMemoize, got plenty of other stuff to work on. Really just responding to your desire to make moize the fastest. Fascinating benchmark differences. Are you running benchmarks in a browser or on the server? Mine are running in Chrome browser. Too bad jsperf.com has disappeared so there could be some commonality.

I will have to add the multi-object stuff and see what benchmarks on my end show. Could actually be a great topic for a joint article/blog post, "Why performance tests differ?".

If you don't respond I will assume you are not interested in further conversation. No worries. There is enough badness out on the Internet I did not want to leave a bad taste in your mouth.

**Comment by anywhichway** [comment]
Hey Tony, you neglected a config option for multi object with iMemoize so no memoization was done. Here is my benchmark:

un-memoized x 8.16 ops/sec ą1.67% (23 runs sampled)
benchmark.html:128 iMemoize.memoize x 21,640,466 ops/sec ą2.62% (56 runs sampled)
benchmark.html:128 lodash _.memoize x 6,789,778 ops/sec ą2.43% (54 runs sampled)
benchmark.html:128 fast-memoize x 5,433,046 ops/sec ą3.59% (50 runs sampled)
benchmark.html:128 moize x 8,267,878 ops/sec ą3.86% (47 runs sampled)
benchmark.html:128 iMemoizedMulti x 16,459,639 ops/sec ą4.68% (46 runs sampled)
benchmark.html:128 moizeMulti x 8,290,546 ops/sec ą4.72% (41 runs sampled)
benchmark.html:128 iMemoizedMultiObject x 20,142,679 ops/sec ą4.47% (44 runs sampled)
benchmark.html:128 moizeMultiObject x 9,706,792 ops/sec ą3.33% (52 runs sampled)

**Comment by planttheidea** [comment]
I actually appreciate you clearing things up a little bit, the way things were worded it initially sounded like a pissing contest ... and like badness, there is enough on the internet that I didn't need any more.

In regards to the technique used, I did actually read the article and looked through the codebase to see what I could glean. I'll admit it is an interesting topic, but more time than I'm willing to invest in this. I threw this together in a few hours for kicks, basically to learn the nitty-gritty aspects of memoization, and when I did benchmarks of it I was pleasantly surprised at the results (I'll happily take being competitive with `lodash` any day). For context, my benchmarks aren't in browser (I didn't invest the time to get benchmarkjs running in the browser), but rather in node (6.9.2). The setup is very similar to what `fast-memoize` was doing.

That said, I will say that while I do strive for speed, there is also a trade-off for a positive DX (developer experience). How developers will consume the API is a very important factor when building a public library, because no matter how brilliant it is people need to *want* to use it, and easily grasp it's basic use. You're absolutely right, I neglected the configuration option. I'm still not entirely certain what that configuration option is, but I think it's `keyProperty`? And because I didn't set that, *no memoization was done*? For a consumer of the library, that kind of blackbox gotcha is a huge negative. With `moize`, you get consistent performance for all datatypes, and there is no additional configuration necessary to get it. Like life, it's a matter of trade-offs ... what I lose in speed by serializing, I gain in simplicity of implementation, which is a huge win for most consumers of it in real-world applications. And let's be honest ... it's no sloth, so for me the pros still outweigh the cons.

Anyway, appreciate you clearing the air, and no hard feelings. Best of luck on your future endeavors.

**Comment by anywhichway** [comment]
Cool. BTW, the reason the keyProperty is required is that if you memoize function calls and pass objects you can get really surprising results if the internals of the object are inspected by the called function and subsequently modified before calling the function again with what appears to be the same object (although that ought to be the end devs problem!).  The keyProperty essentially tells the memoizer to use the value from the keyProperty rather than the object itself. Not memoizing when the keyProperty is not specified is actually a safety feature. Using keyProperty also happens to result in runtime memory use reduction and performance gains because the argument objects actually aren't serialized, just the keys are used. Although, I thoroughly agree with your point about gotchas ... hard call. Indeed, your code is certainly not slothful!

And, the proof is probably in the stars ;-). You have more and fast-memoize has more!
