### ISSUE TITLE
Possible to ignore arguments?

### ISSUE THREAD

**Issue by aduth** [planttheidea/moize#53]
I'm working to upgrade Moize to the 3.x line for a [library of mine](https://github.com/aduth/rememo). I'd previously relied on specifying a custom cache as a hack to be able to ignore the first argument passed to the memoized selector.

See: https://github.com/aduth/rememo/blob/v1.1.1/es/rememo.js#L18-L66

Since the `cache` option has been removed as part of the 3.0 changes, I'm seeking an alternative.

My first thought was to use the `equals` option, but this function is called with the singular arguments to compare, and it's not possible to know the argument's position.

I thought too to use `Function#bind` to prepopulate the first argument for the memoized function without moize considering it, but since the value for the first argument changes frequently in my case, I worry about the performance of using `bind`.

Do you have any recommendations for how I could reimplement this behavior in 3.x ?

**Comment by aduth** [comment]
I've had some success with assigning a custom serializer which closely mimics the default string serializer, with an adjusted starting index. Given degraded performance, ideally I'd not have to resort to serialization.

https://gist.github.com/aduth/cf23ef93b67756f5c4f559843924f39a

**Comment by planttheidea** [comment]
You are indeed correct that the `equals` option is the way to approach this, and as weird as it sounds, so is the `serialize` option! I have a POC that I can show you in a hot second, but first I need to release a fix to a bug in the way that `serialize` implements `equals`. Example coming shortly, with benchmarks.

**Comment by planttheidea** [comment]
Okay! I have updated `moize` with the fix in `3.1.2` that allows `serialize` to work correctly with `equals` (oops), and something like this gist should be what you're looking for:

https://gist.github.com/planttheidea/b447a779a84bc0948af53e435b61bf6c

This example shows how to create a standard shallow equal comparator that specifically skips the first argument of both the new and existing keys, and how to apply it with a custom `serializer` that just does not transform the args at all. The key here is that `serializer` does not need to return a string ... just something that can be uniquely identified, and especially if you pair it with a custom `equals` checker, it can be basically whatever you want.

I chose this particular example because it was the most performant of the various options, running at about 25 million ops / second (based on three args), however it is a highly-targeted and unintuitive way to accomplish what you are looking for. With that in mind, I can easily add in a new option (something like `transformKey`) that would be slightly less performant but more universal and logical in its implementation.

Let me know your thoughts.

**Comment by planttheidea** [comment]
So ... considering the universality and that I could see someone using this for other use-cases than just your example, I went ahead and added the new `transformArgs` option, which does just as described ... transforms the args prior to being used as a key. Wiith this new option, you could do something like:

```javascript
const moized = moize(fn, {
  transformArgs(args) {
    return args.slice(1);
  }
});
```

Much simpler and easy to understand, but it benchmarks at around 5.5 million ops / second ... still quite fast, but a huge drop from the targeted example I gave above. A small tweak that is slightly less readable but more performant:

```javascript
const moized = moize(fn, {
  transformArgs(args) {
    let transformedArgs = [],
        index = args.length;

    while (--index) {
      transformedArgs[index - 1] = args[index];
    }

    return transformedArgs;
  }
});
```

Same result, but benchmarks at about 16 million ops / sec ... still slower than the targeted example, but 3x faster than `slice`. Not trying to sway one direction or another, just providing options based on what is considered priority for your project (raw speed vs readability).

Let me know if any of these options give you what you're looking for, and if so then I'll close the issue.

**Comment by planttheidea** [comment]
Okay so ... I'm an idiot.

`equals` was not working per the spec for `MultipleParameterCacheKey`, because (as you astutely pointed out) it was being called with singular arguments, when the spec calls for the full key being passed ... I missed you calling this out when I read the issue originally, my apologies. This has been fixed in `3.2.1`, so you should be able to use `equals` as you were intending to prior. As such, I am closing, but feel free to reopen if you continue experiencing problems.

In case you were curious, I benchmarked use of `equals` instead of `transformArgs` and it benchmarks way higher ... like 28 million ops / sec.

**Comment by aduth** [comment]
Hey @planttheidea , thanks so much for the advice, and for the enhancements to `equals` and `transformArgs`. Since I'm already using a shallow equality tool similar to the `isShallowEqualExceptFirst` function in your snippet, I was able to eliminate it in favor of a generalized utility that works well for both cases:

https://gist.github.com/aduth/c646dfcbc52561e23c5ab1d5bb9ee422

Is the `serializer` option needed in this case? It seems to work well without it, but noting since it was included in your original gist.

**Comment by planttheidea** [comment]
@aduth nope! If you are just using `equals` then the use of `serialize` and a custom `serializer` are unnecessary. I basically just kept those comments in there for posterity reasons, but the use of `equals` alone is the recommended way. Sorry for the confusion,
