### ISSUE TITLE
moize.get() does not serialize object keys

### ISSUE THREAD

**Issue by Redsandro** [planttheidea/moize#72]
I assumed using an object as parameter to the moized function creates a cache on the hashed or serialized object. However this is not so:

```js
moize = require('moize')
var test = moize(key => `${key.foo} value`)

test(234)
// 'undefined value'

test.has([234])
// true

test({foo: 'bar'})
// 'bar value'

test.has([{foo: 'bar'}])
// false
// expected: true

test.keys()
// [ StandardCacheKey { key: { foo: 'bar' }, size: 1 },
//   StandardCacheKey { key: 234, size: 1 } ]
```

Apparently, the object reference is checked:

```js
var o = {foo: 'wobble'}
test(o)
// 'wobble value'

test.has([o])
// true
```

Sometimes you don't have the reference anymore. You just want the cached value of memoized function that would be given using a different object with the same contents, and you want to be able to see if said object was previously cached using `has()`.

Ugly workaround to illustrate expected behavior:

```js
var test = moize(key => `${JSON.parse(key).foo} value`)

test(JSON.stringify({foo: 'bar'}))
// 'bar value'

test.has([JSON.stringify({foo: 'bar'})])
// true
```

**Comment by planttheidea** [comment]
For both performance and accuracy reasons, serialization has not been the default since version 1.x.x, which is why your match attempt is failing. If you want to use the standard caching technique, then using `has` as you describe in your workaround is a way to accomplish this (but is imperfect, for example if you have function parameters).

If you are going to use `has` in this way, you may consider using `moize.serialize` which will serialize the parameters as you originally assumed. This is slower and potentially less accurate depending on usage, but will avoid the manual stringification on use of `has`.

**Comment by Redsandro** [comment]
Hi @planttheidea, thank you for explaining.

How do you suggest using `moize.serialize` without breaking the moized function? Or would I need to `moize.unserialize` inside the moized function?

In other words, could you write a micro example of what you mean?

**Comment by planttheidea** [comment]
Sure, although I'm not quite sure what you mean by "breaking the moized function", so if I don't answer your question as you were hoping I'd appreciate some clarity there so I can answer it better. If I understand it correctly, you are interpreting it as something that you applied to an already-moized function, but in reality it is the way that you create the moize function.

Basically, `moize.serialize` is another way to create a moized method, and works the same as the standard `moize` method (it is actually a shorthand for passing `{serialize: true}` as an option to `moize`, [as the documentation calls out](https://github.com/planttheidea/moize#serialize)), with the only difference being that the cache key that is stored is serialized as JSON before storage.

```javascript
const dummyExample = (foo) => {
  return {
    foo
  };
};

const array = ['foo'];
const clone = ['foo']; // same value, different object

// standard moizing
const moized = moize(dummy);

moized(array);
moized.keys(); // ['foo']
moized(clone); // will not pull from cache, as it is a new object
moized.has([clone]); // false, as it is a new object

// serialized moizing
const serialMoized = moize.serialize(dummy);

serialMoized(array);
serialMoized.keys(); // "[\"foo\"]"
serialMoized(clone); // will pull from cache, as the stringified value is the same
serialMoized.has([clone]); // true, the stringified value is the same
```

There is no need to unserialize or anything like that ... the key reconciliation is all handled internally, because its an option of how to set up the key structure.

The things to keep in mind are that using serialization as the basis for creating the cache key suffers from the same limitations that `JSON.stringify` itself suffer from:
* functions will not be serialized by default (hence the [`serializeFunctions`](https://github.com/planttheidea/moize#serializefunctions) option)
* order of keys in objects are not guaranteed (this is an aspect of the ES5 spec)
* It is slower (in the case of large objects, [much slower[(https://github.com/planttheidea/moize#multiple-parameters-complex-objects))

This is why I don't recommend using serialization by default.

Another (better, in my opinion) alternative you could use would be to create the `moize` method with a custom [equals](https://github.com/planttheidea/moize#equals) option, such as `isEqual` provided by `lodash`:

```javascript
import isEqual from 'lodash/isEqual';
import moize from 'moize';

const dummyExample = (foo) => {
  return {
    foo
  };
};

const array = ['foo'];
const clone = [...array];

const deepEqualMoized = moize(dummyExample, {equals: isEqual});

deepEqualMoized(array);
deepEqualMoized.keys(); // ['foo']
deepEqualMoized(clone); // will pull from cache, as it has the same deep-equal values
deepEqualMoized.has([clone]); // true, as it has the same deep-equal values
```

This will not have the same aforementioned limitations of serialization, and maintains a high level of performance (depending on the `equals` method you use, but `lodash/isEqual` is one that I've perf tested and its quite fast). The only caveat here is additional dependencies / code to provide the custom `equals` function, and depending on your project I don't know how much of a burden this would be.

I hope these examples and explanations help, but if you would like more details let me know and I'll do my best.

**Comment by Redsandro** [comment]
@planttheidea this is awesome. I misunderstood how I should use this, and I am very glad I asked.

Thank you.  :+1:

**Comment by planttheidea** [comment]
Glad I could help!
