### ISSUE TITLE
Should moize cache promises when `isPromise: true`?

### ISSUE THREAD

**Issue by vlad-zhukov** [planttheidea/moize#80]
Currently `moize` caches promises and it's not possible to get values from cache synchronously. What do you think about changing it like so:

```js
const moized = moize.promise((arg) => Promise.resolve({item: arg}))

// This stays the same
moized('foo').then((value) => {
	console.log(value); // {item: 'foo'}
})

// I propose the following change
console.log(moized.values()) // [{item: 'foo'}] instead of [Promise]

// Also in that case makes sense to add a `get` method
console.log(moized.get('foo')) // {item: 'foo'}
```

What do you think?

**Comment by planttheidea** [comment]
The whole point of caching the promise is because it maintains the contract of the function return. What you are proposing would not actually work the way you've written it:

* The `Promise` spec explicitly disallows the ability to introspect the value from a promise, even when resolved
* If the cache was manually manipulated so that `moize.get()` (which wouldn't be added ... it already exists) returns the value itself instead of the promise that resolves to that value, the cached function would no longer be `then`able

Not saying it is impossible, but it is not something expected (as it is not how the spec operates) and would also require some crazy code gymnastics to accomplish what would be a very niche requirement.

You could, however, create your own wrapper to accomplish this feat:

```javascript
// create a wrapper that will store the resolved value in a custom cache property before returning
const getSyncPromiseMoize = (fn) => {
  const moizedFn = moize.promise((...args) => {
    return fn(...args).then((value) => {
      moizedFn.synchronousCache.set(arg, value);

      return value;
    });
  });

  moizedFn.synchronousCache = new Map();

  return moizedFn;
};

const moized = getSyncPromiseMoize((arg) => Promise.resolve({item: arg}));

moized('foo').then((value) => {
  console.log(value); // {item: 'foo'}
});

// later in your code
console.log(moized.synchronousCache.get('foo')); // {item: 'foo'}
```

I do not want to do this on the main library because I consider this a very rare (and honestly somewhat misleading) use-case, but a simple wrapper should give you what you seek for your application.
